version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crm-postgres
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user -d crm_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./crm-backend
      dockerfile: Dockerfile
    container_name: crm-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://postgres:5432/crm_db
      DATABASE_USERNAME: crm_user
      DATABASE_PASSWORD: crm_password
      JWT_SECRET: your-production-secret-key-minimum-256-bits-long-change-me-in-production
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - crm-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  crm-network:
    driver: bridge
