spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_db
    username: crm_user
    password: crm_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # Flyway manages schema
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 28080
  error:
    include-message: always
    include-stacktrace: always

logging:
  level:
    com.empresa.crm: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
